// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZc5lOWzEM6MgABVkxxPcrVFxROUqynz4',
    appId: '1:408939726489:web:1c586e46355485cf84da08',
    messagingSenderId: '408939726489',
    projectId: 'appfirst-49951',
    authDomain: 'appfirst-49951.firebaseapp.com',
    storageBucket: 'appfirst-49951.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzeZvVDYfwprad9dnT4KUrhNypfyvY-OE',
    appId: '1:408939726489:android:a313bf29fe7a8b7784da08',
    messagingSenderId: '408939726489',
    projectId: 'appfirst-49951',
    storageBucket: 'appfirst-49951.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoZOSeUNgs5ItTGKN94o5KQGz1rmXq-Cc',
    appId: '1:408939726489:ios:0a52f241d93eb22384da08',
    messagingSenderId: '408939726489',
    projectId: 'appfirst-49951',
    storageBucket: 'appfirst-49951.appspot.com',
    iosClientId: '408939726489-ohnt26kr59hjg8j3grqkknea46n5562p.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoZOSeUNgs5ItTGKN94o5KQGz1rmXq-Cc',
    appId: '1:408939726489:ios:0a52f241d93eb22384da08',
    messagingSenderId: '408939726489',
    projectId: 'appfirst-49951',
    storageBucket: 'appfirst-49951.appspot.com',
    iosClientId: '408939726489-ohnt26kr59hjg8j3grqkknea46n5562p.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
